# File: .github/workflows/repo-sync.yml

name: 同步上游仓库
on:
  schedule:
    - cron: '0 8 */2 * *'
  watch:
    types: started
  repository_dispatch:
    types: sync-repo
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync ACL4SSR-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ACL4SSR/ACL4SSR.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}

      - name: sync TikTok_Unlock-scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/cyubuchen/TikTok_Unlock.git"
          source_branch: "master"        # mySelf仓库的分支
          destination_branch: "master"   # 你自己远程的分支
          github_token: ${{ secrets.PAT }}
      
      - name: sync Rules-For-Quantumult-X-Rules
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/sve1r/Rules-For-Quantumult-X.git"
          source_branch: "master"
          destination_branch: "develop"
          github_token: ${{ secrets.PAT }}  
